import type { UiLanguage } from "./uiLanguage";

export const UI_COPY: Record<string, Record<UiLanguage, string>> = {
  "common.cancel": { en: "Cancel", ko: "취소" },
  "common.close": { en: "Close", ko: "닫기" },
  "common.save": { en: "Save", ko: "저장" },
  "common.saving": { en: "Saving...", ko: "저장 중..." },
  "common.create": { en: "Create", ko: "생성" },
  "common.delete": { en: "Delete", ko: "삭제" },
  "common.edit": { en: "Edit", ko: "수정" },
  "common.rename": { en: "Rename", ko: "이름 변경" },
  "common.loading": { en: "Loading...", ko: "불러오는 중..." },
  "common.saved": { en: "Saved", ko: "저장됨" },
  "common.done": { en: "Done", ko: "완료" },
  "common.all": { en: "All", ko: "전체" },
  "common.active": { en: "Active", ko: "진행 중" },
  "common.search": { en: "Search...", ko: "검색..." },
  "common.ungrouped": { en: "Ungrouped", ko: "미분류" },
  "common.settings": { en: "Settings", ko: "설정" },
  "common.dashboard": { en: "Dashboard", ko: "대시보드" },
  "common.localMode": { en: "Local Mode", ko: "로컬 모드" },
  "error.somethingWentWrong": { en: "Something went wrong", ko: "문제가 발생했습니다" },
  "error.inLabel": { en: " in {label}", ko: " ({label})" },
  "error.unknown": { en: "Unknown error", ko: "알 수 없는 오류" },
  "error.retry": { en: "Retry", ko: "다시 시도" },
  "error.label.brief tab": { en: "brief tab", ko: "Brief 탭" },
  "error.label.agent tab": { en: "agent tab", ko: "Ideation 탭" },
  "error.label.assets tab": { en: "assets tab", ko: "Assets 탭" },
  "error.label.storyboard tab": { en: "storyboard tab", ko: "Conti 탭" },
  "error.label.App": { en: "App", ko: "앱" },

  "nav.projectWorkspace": { en: "Project Workspace", ko: "프로젝트 워크스페이스" },
  "nav.localUser": { en: "Local User", ko: "로컬 사용자" },

  "settings.title": { en: "Settings", ko: "설정" },
  "settings.saveSettings": { en: "Save Settings", ko: "설정 저장" },
  "settings.apiKeys": { en: "API Keys", ko: "API 키" },
  "settings.modelsPrefs": { en: "Models & Preferences", ko: "모델 및 환경설정" },
  "settings.models": { en: "Models", ko: "모델" },
  "settings.preferences": { en: "Preferences", ko: "환경설정" },
  "settings.required": { en: "REQUIRED", ko: "필수" },
  "settings.briefModel": { en: "Brief Analysis Model", ko: "Brief 분석 모델" },
  "settings.briefModelDesc": {
    en: "Model used to analyze brief text + images/video. Takes effect from the next analysis.",
    ko: "Brief 텍스트와 이미지/영상을 분석할 때 사용할 모델입니다. 다음 분석부터 적용됩니다.",
  },
  "settings.agentModel": { en: "Agent Chat Model", ko: "Agent 채팅 모델" },
  "settings.agentModelDesc": {
    en: "Model used in agent chat (storylines / storyboard). Takes effect from your next message.",
    ko: "Agent 채팅(스토리라인/스토리보드)에 사용할 모델입니다. 다음 메시지부터 적용됩니다.",
  },
  "settings.uiLanguage": { en: "UI Language", ko: "UI 언어" },
  "settings.uiLanguageDesc": {
    en: "Controls app labels, buttons, dialogs, and toasts. Brief analysis output still follows the KO/EN toggle in the Brief tab.",
    ko: "앱의 라벨, 버튼, 팝업, 알림 언어를 바꿉니다. Brief 분석 결과 언어는 Brief 탭의 KO/EN 토글을 따릅니다.",
  },
  "settings.dashboardCardsPerRow": { en: "Dashboard project columns", ko: "대시보드 프로젝트 열 수" },
  "settings.dashboardCardsPerRowDesc": {
    en: "Choose how many project cards appear in each dashboard row. Default is 6.",
    ko: "대시보드에서 한 줄에 보여줄 프로젝트 카드 개수를 설정합니다. 기본값은 6개입니다.",
  },
  "settings.dashboardCardsPerRowOption": { en: "{count} columns", ko: "{count}개" },
  "settings.korean": { en: "Korean (KO)", ko: "한국어 (KO)" },
  "settings.english": { en: "English (EN)", ko: "영어 (EN)" },

  "dashboard.allProjects": { en: "All Projects", ko: "전체 프로젝트" },
  "dashboard.newProject": { en: "New Project", ko: "새 프로젝트" },
  "dashboard.newFolder": { en: "New Folder", ko: "새 폴더" },
  "dashboard.editFolder": { en: "Edit Folder", ko: "폴더 수정" },
  "dashboard.folderName": { en: "Folder Name *", ko: "폴더명 *" },
  "dashboard.noProjects": { en: "No projects yet", ko: "아직 프로젝트가 없습니다" },
  "dashboard.noProjectsDesc": { en: "Create your first project to begin.", ko: "첫 프로젝트를 만들어 시작하세요." },
  "dashboard.deleteProjectTitle": { en: "Delete this project?", ko: "이 프로젝트를 삭제할까요?" },
  "dashboard.deleteProjectDesc": { en: "All data will be permanently deleted.", ko: "모든 데이터가 영구적으로 삭제됩니다." },
  "dashboard.noDeadline": { en: "No Deadline", ko: "마감일 없음" },
  "dashboard.thumbnailAdjusted": { en: "Thumbnail adjusted", ko: "썸네일 위치가 조정되었습니다" },
  "dashboard.editThumbnail": { en: "Adjust thumbnail", ko: "썸네일 위치 조정" },
  "dashboard.folders": { en: "Folders", ko: "폴더" },
  "dashboard.noFolders": { en: "No folders yet", ko: "아직 폴더가 없습니다" },
  "dashboard.noResults": { en: "No results", ko: "검색 결과가 없습니다" },
  "dashboard.noResultsDesc": { en: "Try a different search or filter.", ko: "다른 검색어나 필터를 시도해보세요." },
  "dashboard.serverOnline": { en: "Server: Online", ko: "서버: 온라인" },
  "dashboard.projectsCount": { en: "Projects: {count}", ko: "프로젝트: {count}" },

  "project.editTitle": { en: "Edit title", ko: "제목 수정" },
  "project.department": { en: "Dept", ko: "요청 부서" },
  "project.departmentPlaceholder": { en: "DEPARTMENT", ko: "요청 부서" },
  "project.deadline": { en: "Deadline", ko: "마감일" },
  "project.clearDeadline": { en: "Clear deadline", ko: "마감일 지우기" },
  "project.startTitle": { en: "Where would you like to start?", ko: "어디서부터 시작할까요?" },
  "project.startDesc": { en: "Pick a stage to jump straight into work.", ko: "바로 작업할 단계를 선택하세요." },
  "project.briefDesc": { en: "Analyze the brief to kick off the project", ko: "Brief를 분석해 프로젝트를 시작합니다" },
  "project.assetsDesc": { en: "Register characters, items and backgrounds", ko: "캐릭터, 아이템, 배경을 등록합니다" },
  "project.agentDesc": { en: "Shape shots through AI conversation", ko: "AI 대화로 컷 구성을 만듭니다" },
  "project.contiDesc": { en: "Generate storyboard images", ko: "스토리보드 이미지를 생성합니다" },

  "tabs.brief": { en: "Brief", ko: "Brief" },
  "tabs.assets": { en: "Assets", ko: "Assets" },
  "tabs.agent": { en: "Ideation", ko: "Ideation" },
  "tabs.conti": { en: "Conti", ko: "Conti" },

  "projectModal.createTitle": { en: "Create Project", ko: "프로젝트 생성" },
  "projectModal.editTitle": { en: "Edit Project", ko: "프로젝트 수정" },
  "projectModal.projectName": { en: "Project Name *", ko: "프로젝트명 *" },
  "projectModal.projectNamePlaceholder": { en: "Project name", ko: "프로젝트명" },
  "projectModal.department": { en: "Department", ko: "요청 부서" },
  "projectModal.departmentPlaceholder": { en: "Department name", ko: "요청 부서명" },
  "projectModal.deadline": { en: "Deadline", ko: "마감일" },
  "projectModal.pickDate": { en: "Pick a date", ko: "날짜 선택" },
  "projectModal.status": { en: "Status", ko: "상태" },
  "projectModal.inProgress": { en: "In Progress", ko: "진행 중" },
  "projectModal.completed": { en: "Completed", ko: "완료" },
  "projectModal.folder": { en: "Folder", ko: "폴더" },
  "projectModal.format": { en: "Format", ko: "포맷" },
  "projectModal.style": { en: "Style", ko: "스타일" },

  "export.title": { en: "Export", ko: "내보내기" },
  "export.format": { en: "Format", ko: "형식" },
  "export.version": { en: "Version", ko: "버전" },
  "export.currentWork": { en: "Current work", ko: "현재 작업" },
  "export.resolution": { en: "Resolution", ko: "해상도" },
  "export.exportMode": { en: "Export mode", ko: "내보내기 방식" },
  "export.pageLayout": { en: "Page layout", ko: "페이지 레이아웃" },
  "export.pageLayoutDesc": { en: "Storyboard sheet", ko: "스토리보드 시트" },
  "export.individualScenes": { en: "Individual shots", ko: "개별 컷" },
  "export.individualScenesDesc": { en: "Per-shot PNG files", ko: "컷별 PNG 파일" },
  "export.cardsPerRow": { en: "Cards per row", ko: "한 줄 컷 수" },
  "export.includeMetadata": {
    en: "Include metadata (title, camera, mood, location, runtime)",
    ko: "메타데이터 포함 (제목, Camera, Mood, Location, 러닝타임)",
  },
  "export.exportCta": { en: "Export {format} ({count})", ko: "{format} 내보내기 ({count})" },

  "studio.view": { en: "View", ko: "보기" },
  "studio.editor": { en: "Editor", ko: "에디터" },
  "studio.inpaint": { en: "Inpaint", ko: "인페인트" },
  "studio.sketches": { en: "Sketches", ko: "스케치" },
  "studio.history": { en: "History", ko: "히스토리" },
  "studio.compare": { en: "Compare", ko: "비교" },
  "studio.regenerate": { en: "Regenerate", ko: "재생성" },
  "studio.download": { en: "Download", ko: "다운로드" },
  "studio.loadingImage": { en: "Loading image...", ko: "이미지 불러오는 중..." },
  "studio.failedLoadImage": { en: "Failed to load image", ko: "이미지를 불러오지 못했습니다" },
  "studio.noContiImage": { en: "No conti image", ko: "콘티 이미지 없음" },
  "studio.brush": { en: "Brush", ko: "브러시" },
  "studio.eraser": { en: "Eraser", ko: "지우개" },
  "studio.size": { en: "Size", ko: "크기" },
  "studio.strength": { en: "Strength", ko: "강도" },
  "studio.reset": { en: "Reset", ko: "초기화" },
  "studio.brushSizeTitle": { en: "Brush size (image-pixel radius)", ko: "브러시 크기 (이미지 픽셀 기준 반경)" },
  "studio.brushRadiusTitle": {
    en: "Brush radius: {size} px (image). Shortcuts: [ and ]",
    ko: "브러시 반경: {size}px (이미지 기준). 단축키: [ / ]",
  },
  "studio.imagePixelRadiusTitle": { en: "Image-pixel radius (resolution-independent)", ko: "해상도와 무관한 이미지 픽셀 반경" },
  "studio.editStrengthTitle": { en: "Edit strength - lower = subtler edit, preserves more original", ko: "수정 강도 - 낮을수록 원본을 더 보존합니다" },
  "studio.editStrengthValueTitle": {
    en: "Edit strength: {strength}%. Lower = preserves more original. Shortcuts: Shift+[ and Shift+]",
    ko: "수정 강도: {strength}%. 낮을수록 원본을 더 보존합니다. 단축키: Shift+[ / Shift+]",
  },
  "studio.lowerStrengthTitle": { en: "Lower strength = subtler edit, original structure preserved", ko: "강도가 낮을수록 변화가 부드럽고 원본 구조를 유지합니다" },
  "studio.undoTitle": { en: "Undo (Ctrl+Z)", ko: "실행 취소 (Ctrl+Z)" },
  "studio.clearMaskTitle": { en: "Clear mask", ko: "마스크 지우기" },
  "studio.resetZoomTitle": { en: "Reset zoom (0)", ko: "줌 초기화 (0)" },
  "studio.generating": { en: "Generating...", ko: "생성 중..." },
  "studio.promptPlaceholder": {
    en: "Describe changes... (type @ to tag an asset)",
    ko: "변경할 내용을 입력하세요... (@로 에셋 태그)",
  },
  "studio.modifyPaintedArea": { en: "Modify painted area", ko: "칠한 영역만 수정" },
  "studio.modifyEntireImage": { en: "Modify entire image", ko: "전체 이미지 수정" },
  "studio.dropReferenceImages": { en: "Drop images to add as reference", ko: "이미지를 놓아 레퍼런스로 추가" },
  "studio.images": { en: "Images", ko: "이미지" },
  "studio.editImage": { en: "Edit Image", ko: "이미지 수정" },
  "studio.moodReference": { en: "Mood Reference", ko: "무드 레퍼런스" },
  "studio.sketchModelNanoDesc": {
    en: "Best default · Uses asset images for stable character/background likeness",
    ko: "기본 추천 · 에셋 이미지를 참고해 캐릭터/배경 외형을 안정적으로 반영",
  },
  "studio.sketchModelGpt2Desc": {
    en: "High quality vision · Strong reference reading, slower generation",
    ko: "고품질 비전 · 참조 이미지를 강하게 읽지만 생성 속도는 느림",
  },
  "studio.sketchModelGpt15Desc": {
    en: "Faster vision · Reads asset images with lighter reference fidelity",
    ko: "빠른 비전 · 에셋 이미지를 읽되 참조 반영은 비교적 가벼움",
  },
  "studio.default": { en: "DEFAULT", ko: "기본" },
  "studio.registerAssetsFirst": { en: "Register asset images first", ko: "먼저 이미지가 있는 에셋을 등록하세요" },
  "studio.decreaseCount": { en: "Decrease count", ko: "개수 줄이기" },
  "studio.increaseCount": { en: "Increase count", ko: "개수 늘리기" },
  "studio.sketchCount": { en: "Sketch count", ko: "스케치 개수" },
  "studio.showAllSketches": { en: "Show all sketches", ko: "전체 스케치 보기" },
  "studio.showLikedOnly": { en: "Show liked only", ko: "저장한 항목만 보기" },
  "studio.savedCount": { en: "Saved {count}", ko: "저장됨 {count}" },
  "studio.galleryColumns": { en: "Gallery columns", ko: "갤러리 열 수" },
  "studio.colsTitle": { en: "{count} col", ko: "{count}열" },
  "studio.otherModelsGenerating": {
    en: "Other model(s) generating in the background - switch model anytime.",
    ko: "다른 모델이 백그라운드에서 생성 중입니다. 언제든 모델을 바꿀 수 있습니다."
  },
  "studio.modelRequiresAssets": {
    en: "{model} requires registered assets.",
    ko: "{model}은 이미지가 있는 에셋이 필요합니다."
  },
  "studio.noSketchesYet": { en: "No sketches yet", ko: "아직 스케치가 없습니다" },
  "studio.noSketchesDesc": {
    en: "Generate composition candidates for shot #{scene} based on its description. Pick the best one and promote it to this shot's image.",
    ko: "컷 #{scene}의 설명을 바탕으로 구도 후보를 생성하세요. 마음에 드는 이미지를 이 컷의 이미지로 적용할 수 있습니다."
  },
  "studio.noSavedSketches": { en: "No saved sketches", ko: "저장한 스케치가 없습니다" },
  "studio.noSavedSketchesDesc": {
    en: "Hover a sketch and tap the heart to save it. Switch off Saved to see all {count} sketches again.",
    ko: "스케치에 마우스를 올리고 하트를 눌러 저장하세요. 저장됨 필터를 끄면 전체 {count}개 스케치를 다시 볼 수 있습니다."
  },
  "studio.unlike": { en: "Unlike", ko: "저장 취소" },
  "studio.like": { en: "Like", ko: "저장" },
  "studio.setAsSceneImage": { en: "Set as shot image", ko: "컷 이미지로 설정" },
  "studio.use": { en: "Use", ko: "사용" },
  "studio.registerAssetsFirstTitle": { en: "Register assets first", ko: "먼저 에셋을 등록하세요" },
  "studio.sketchGenerationFailed": { en: "Sketch generation failed", ko: "스케치 생성 실패" },
  "studio.noSketchesGenerated": { en: "No sketches generated", ko: "생성된 스케치가 없습니다" },
  "studio.noSketchesGeneratedDesc": {
    en: "All shots failed upstream. Check the logs and try again - switching to a different model often helps.",
    ko: "모든 샷 생성이 실패했습니다. 로그를 확인한 뒤 다시 시도하세요. 다른 모델로 바꾸면 해결되는 경우가 많습니다."
  },
  "studio.partialSketchesGenerated": {
    en: "{done}/{total} sketches generated",
    ko: "스케치 {done}/{total}개 생성됨"
  },
  "studio.partialSketchesFailed": {
    en: "{count} shot(s) failed upstream and were skipped.",
    ko: "{count}개 샷이 생성 실패로 건너뛰어졌습니다."
  },
  "studio.sketchesGenerated": { en: "{count} sketch(es) generated", ko: "스케치 {count}개 생성됨" },
  "studio.sceneImageReplaced": { en: "Shot image replaced", ko: "컷 이미지 교체됨" },
  "studio.failedSetSceneImage": { en: "Failed to set shot image", ko: "컷 이미지 설정 실패" },
  "studio.inpaintComplete": { en: "Inpainting complete", ko: "Inpaint 완료" },
  "studio.inpaintFailed": { en: "Inpainting failed", ko: "Inpaint 실패" },
  "studio.regenComplete": { en: "Regeneration complete", ko: "재생성 완료" },
  "studio.regenFailed": { en: "Regeneration failed", ko: "재생성 실패" },

  "agent.createSceneCards": { en: "Create shot cards", ko: "컷 카드 생성" },
  "agent.createSceneHelp": {
    en: "Replace starts fresh. Append keeps existing shots and adds drafts after them.",
    ko: "Replace는 기존 컷을 지우고 새로 시작합니다. Append는 기존 컷 뒤에 draft를 추가합니다.",
  },
  "agent.sceneCounts": { en: "{existing} existing shots · {pending} draft shots", ko: "기존 컷 {existing}개 · draft 컷 {pending}개" },
  "agent.replaceExisting": { en: "Replace existing ({count})", ko: "기존 컷 교체 ({count})" },
  "agent.replaceDesc": { en: "Start fresh with draft shots", ko: "draft 컷으로 새로 시작" },
  "agent.append": { en: "Append ({count} total)", ko: "뒤에 추가 (총 {count}개)" },
  "agent.appendDesc": { en: "Keep current shots and add drafts", ko: "현재 컷을 유지하고 draft를 추가" },
  "agent.sendToConti": { en: "Send to Conti", ko: "Conti로 보내기" },
  "agent.scenesToSend": { en: "Shots to send ({count})", ko: "보낼 컷 ({count}개)" },
  "agent.versionName": { en: "Version Name", ko: "버전 이름" },
  "agent.versionPlaceholder": { en: "Auto-generated if empty", ko: "비워두면 자동 생성" },
  "agent.sending": { en: "Sending...", ko: "보내는 중..." },
  "agent.noScenesToSend": { en: "No shots to send", ko: "보낼 컷이 없습니다" },
  "agent.sendFailed": { en: "Send failed", ko: "보내기 실패" },
  "agent.sentToConti": { en: "\"{name}\" sent to Conti tab", ko: "\"{name}\" Conti 탭으로 전송됨" },
  "agent.loadContiVersion": { en: "Load conti version", ko: "Conti 버전 불러오기" },
  "agent.noContiVersions": {
    en: "No saved conti versions yet.\nCreate a conti draft in the Conti tab first.",
    ko: "저장된 Conti 버전이 아직 없습니다.\n먼저 Conti 탭에서 draft를 생성하세요.",
  },
  "agent.loadVersionHelp": { en: "Loading a version replaces the current shot composition.", ko: "버전을 불러오면 현재 컷 구성이 교체됩니다." },
  "agent.selectVersion": { en: "Select a saved version to load.", ko: "불러올 저장 버전을 선택하세요." },
  "agent.total": { en: "Total {seconds}s", ko: "총 {seconds}s" },
  "agent.more": { en: "+{count} more", ko: "+{count}개 더" },
  "agent.replaceDraftTitle": { en: "Replace with new draft?", ko: "새 draft로 교체할까요?" },
  "agent.replace": { en: "Replace", ko: "교체" },
  "agent.loadVersion": { en: "Load Version", ko: "버전 불러오기" },
  "agent.addScene": { en: "Add Shot", ko: "컷 추가" },
  "agent.deleteScene": { en: "Delete Shot", ko: "컷 삭제" },
  "agent.versionLoaded": { en: "Version loaded. Keep growing with Agent.", ko: "버전을 불러왔습니다. Agent에서 계속 작업하세요." },
  "agent.failedSaveScenes": { en: "Failed to save shots", ko: "컷 저장 실패" },
  "agent.scenesConfirmed": { en: "{count} shot(s) confirmed.", ko: "컷 {count}개가 확정되었습니다." },
  "agent.failedSendMessage": { en: "Failed to send message", ko: "메시지 전송 실패" },
  "agent.sceneOrderUpdated": { en: "Shot order updated.", ko: "컷 순서가 변경되었습니다." },
  "agent.failedAddScene": { en: "Failed to add shot", ko: "컷 추가 실패" },
  "agent.failedInsertScene": { en: "Failed to insert shot", ko: "컷 삽입 실패" },
  "agent.createSceneCardsFromDraft": { en: "Create shot cards from this draft", ko: "이 draft로 컷 카드 생성" },

  "assets.newAsset": { en: "New Asset", ko: "새 에셋" },
  "assets.editAsset": { en: "Edit Asset", ko: "에셋 수정" },
  "assets.deleteAsset": { en: "Delete Asset", ko: "에셋 삭제" },
  "assets.character": { en: "Character", ko: "캐릭터" },
  "assets.item": { en: "Item", ko: "아이템" },
  "assets.background": { en: "Background", ko: "배경" },
  "assets.type": { en: "Type", ko: "유형" },
  "assets.tagName": { en: "Tag Name", ko: "태그 이름" },
  "assets.tagUsage": { en: "Tag as @{tag} in chat and shot descriptions", ko: "채팅과 컷 설명에서 @{tag}로 태그하세요" },
  "assets.visualSource": { en: "Visual Source", ko: "비주얼 소스" },
  "assets.uploadPhoto": { en: "Upload Photo", ko: "사진 업로드" },
  "assets.uploadPhotoDesc": { en: "Best for consistent portrayal", ko: "일관된 묘사에 적합" },
  "assets.aiGenerated": { en: "AI Generated", ko: "AI 생성" },
  "assets.aiGeneratedDesc": { en: "Create instantly", ko: "바로 생성" },
  "assets.analyzing": { en: "Analyzing...", ko: "분석 중..." },
  "assets.analyzingOutfit": { en: "Analyzing outfit...", ko: "의상 분석 중..." },
  "assets.autoAnalyzeOutfit": { en: "Auto-analyze outfit from image", ko: "이미지에서 의상 자동 분석" },
  "assets.autoAnalyzeItem": { en: "Auto-analyze item from image", ko: "이미지에서 아이템 자동 분석" },
  "assets.autoAnalyzeLocation": { en: "Auto-analyze location from image", ko: "이미지에서 장소 자동 분석" },
  "assets.descriptionInput": { en: "Description Input", ko: "설명 입력" },
  "assets.characterAppearancePlaceholder": { en: "Describe the character's appearance", ko: "캐릭터 외형을 입력하세요" },
  "assets.generateAiDescription": { en: "Generate AI Description", ko: "AI 설명 생성" },
  "assets.generatingAiDescription": { en: "Generating AI description...", ko: "AI 설명 생성 중..." },
  "assets.appearanceDescription": { en: "Appearance Description (English, editable)", ko: "외형 설명 (영어, 수정 가능)" },
  "assets.generateCharacterImage": { en: "Generate Character Image", ko: "캐릭터 이미지 생성" },
  "assets.generatingImage": { en: "Generating image...", ko: "이미지 생성 중..." },
  "assets.saving": { en: "Saving...", ko: "저장 중..." },
  "assets.noDescription": { en: "No description", ko: "설명 없음" },
  "assets.noOutfitInfo": { en: "No outfit info", ko: "의상 정보 없음" },
  "assets.deleteToast": { en: "Deleted", ko: "삭제됨" },
  "assets.updatedToast": { en: "Updated", ko: "수정됨" },
  "assets.registeredToast": { en: "{type} registered", ko: "{type} 등록됨" },
  "assets.saveFailed": { en: "Save failed", ko: "저장 실패" },
  "assets.focalSaveFailed": { en: "Profile image adjustment was not saved", ko: "프로필 이미지 조정이 저장되지 않았습니다" },
  "assets.maxFileSize": { en: "Max file size is 5MB", ko: "최대 파일 크기는 5MB입니다" },
  "assets.noAnalysisResult": { en: "No analysis result", ko: "분석 결과 없음" },
  "assets.noAnalysisDesc": { en: "Could not extract info from image.", ko: "이미지에서 정보를 추출하지 못했습니다." },
  "assets.imageAnalysisFailed": { en: "Image analysis failed", ko: "이미지 분석 실패" },
  "assets.aiDescriptionFailed": { en: "AI description failed", ko: "AI 설명 생성 실패" },
  "assets.imageGenerationFailed": { en: "Image generation failed", ko: "이미지 생성 실패" },
  "assets.itemDetail": { en: "Item Detail", ko: "아이템 상세" },
  "assets.rolePlaceholder": { en: "Character's role and personality", ko: "캐릭터의 역할과 성격" },
  "assets.roleHelp": {
    en: "Used as character relationship context when composing stories with the agent",
    ko: "Agent가 스토리를 구성할 때 캐릭터 관계 맥락으로 사용됩니다",
  },
  "assets.optional": { en: "optional", ko: "선택" },
  "assets.optionalAuto": { en: "optional / auto-analyzable", ko: "선택 / 자동 분석 가능" },
  "assets.outfitStyle": { en: "Outfit / Style", ko: "의상 / 스타일" },
  "assets.outfitPlaceholder": { en: "Outfit and styling details", ko: "의상과 스타일 디테일" },
  "assets.itemPlaceholder": { en: "Describe the item in detail", ko: "아이템을 자세히 설명하세요" },
  "assets.locationPlaceholder": { en: "Describe the location and atmosphere", ko: "장소와 분위기를 설명하세요" },
  "assets.dropHere": { en: "Drop Here", ko: "여기에 드롭" },
  "assets.dragOrClick": { en: "Drag or Click · Max 5MB", ko: "드래그 또는 클릭 · 최대 5MB" },
  "assets.deleteAssetDesc": {
    en: "Are you sure you want to delete this asset? This action cannot be undone.",
    ko: "이 에셋을 삭제할까요? 이 작업은 되돌릴 수 없습니다.",
  },
  "assets.generateCameraFramings": { en: "Generate Camera Framings", ko: "카메라 프레이밍 생성" },
  "assets.cameraFramingHelp": {
    en: "Each button creates a standalone background asset. Use the generated @tag in shot Location or Description.",
    ko: "각 버튼은 독립 배경 에셋을 생성합니다. 생성된 @태그를 컷 Location 또는 Description에 사용하세요.",
  },
  "assets.generateAll": { en: "Generate All", ko: "전체 생성" },
  "assets.existingSiblings": { en: "Existing siblings ({count})", ko: "생성된 프레이밍 ({count})" },
  "assets.generatedFramings": { en: "Generated framings appear as sibling @tags.", ko: "생성된 프레이밍은 sibling @태그로 표시됩니다." },
  "assets.zoomHintDrag": { en: "Drag to move · Scroll to zoom", ko: "드래그로 이동 · 스크롤로 줌" },
  "assets.zoomHintClose": { en: "Scroll to zoom · Click outside to close", ko: "스크롤로 줌 · 바깥 클릭으로 닫기" },
  "assets.upgradingLegacy": { en: "upgrading legacy...", ko: "기존 데이터 변환 중..." },
  "assets.framingFailed": { en: "{framing} framing failed", ko: "{framing} 프레이밍 실패" },
  "assets.cameraFramingsUpgraded": { en: "Camera framings upgraded", ko: "카메라 프레이밍 변환 완료" },
  "assets.cameraFramingsUpgradedDesc": {
    en: "{count} stored variation(s) promoted to standalone @tag(s).",
    ko: "저장된 variation {count}개를 독립 @태그로 변환했습니다.",
  },
  "assets.variationMigrationFailed": { en: "Variation migration failed", ko: "Variation 변환 실패" },
  "assets.noSourceImage": { en: "No source image", ko: "원본 이미지 없음" },
  "assets.noSourceImageDesc": { en: "Upload a primary photo before generating framings.", ko: "프레이밍 생성 전에 대표 사진을 업로드하세요." },
  "assets.framingCreated": { en: "Framing created", ko: "프레이밍 생성됨" },
  "assets.framingCreatedDesc": { en: "@{tag} is ready to @-mention in shots.", ko: "@{tag}를 컷에서 멘션할 수 있습니다." },
  "assets.itemDescription": { en: "Item Description", ko: "아이템 설명" },
  "assets.locationDescription": { en: "Location Description", ko: "장소 설명" },
  "assets.characterDescription": { en: "Character Description", ko: "캐릭터 설명" },
  "assets.roleRelationship": { en: "Role / Relationship", ko: "역할 / 관계" },
  "assets.outfit": { en: "Outfit", ko: "의상" },
  "assets.noDescriptionRegistered": { en: "No description registered", ko: "등록된 설명이 없습니다" },
  "assets.usedInScenes": { en: "Used in {count} {unit}", ko: "{count}개 {unit}에서 사용" },
  "assets.scene": { en: "Shot", ko: "컷" },
  "assets.scenes": { en: "Shots", ko: "컷" },
  "assets.addCharacter": { en: "Add Character", ko: "캐릭터 추가" },
  "assets.addItem": { en: "Add Item", ko: "아이템 추가" },
  "assets.addBackground": { en: "Add Background", ko: "배경 추가" },
  "assets.goToIdeation": { en: "Go to Ideation", ko: "Ideation으로 이동" },
  "assets.noCharacters": { en: "No Characters", ko: "캐릭터 없음" },
  "assets.noItems": { en: "No Items", ko: "아이템 없음" },
  "assets.noBackgrounds": { en: "No Backgrounds", ko: "배경 없음" },
  "assets.emptyCharacter": { en: "Register people, models, or recurring cast.", ko: "인물, 모델, 반복 등장 캐릭터를 등록하세요." },
  "assets.emptyItem": { en: "Register products, props, or important objects.", ko: "제품, 소품, 주요 오브젝트를 등록하세요." },
  "assets.emptyBackground": { en: "Register locations or reusable backgrounds.", ko: "장소나 재사용 배경을 등록하세요." },
  "assets.adjustFocalPoint": { en: "Adjust focal point", ko: "초점 위치 조정" },
  "assets.clickGenerateFramings": { en: "Click to generate camera framings", ko: "클릭해서 카메라 프레이밍 생성" },
  "assets.framingsGenerated": { en: "{count} framing(s) generated", ko: "프레이밍 {count}개 생성됨" },

  "brief.creativeInput": { en: "Creative Input", ko: "크리에이티브 입력" },
  "brief.briefText": { en: "Brief Text", ko: "브리프 텍스트" },
  "brief.reference": { en: "Reference", ko: "레퍼런스" },
  "brief.ideaNote": { en: "Idea Note", ko: "아이디어 노트" },
  "brief.optional": { en: "Optional", ko: "선택" },
  "brief.reAnalyze": { en: "Re-analyze", ko: "다시 분석" },
  "brief.analyzing": { en: "Analyzing...", ko: "분석 중..." },
  "brief.executeAnalysis": { en: "Execute Analysis", ko: "분석 실행" },
  "brief.strategyManifesto": { en: "Strategy Manifesto", ko: "전략 분석" },
  "brief.noAnalysisYet": { en: "No Analysis Yet", ko: "아직 분석 없음" },
  "brief.inputBriefExecute": { en: "Input brief -> Execute Analysis", ko: "브리프 입력 -> 분석 실행" },
  "brief.analysisComplete": { en: "Analysis Complete", ko: "분석 완료" },
  "brief.executeStrategy": { en: "Execute Strategy", ko: "전략 실행" },
  "brief.copy": { en: "Copy", ko: "복사" },
  "brief.nextStep": { en: "Next Step", ko: "다음 단계" },
  "brief.runAnalysisFirst": { en: "Run analysis first to proceed", ko: "진행하려면 먼저 분석을 실행하세요" },
  "brief.briefPlaceholder": {
    en: "Enter your brief - production goals, target audience, key message, references, etc.",
    ko: "브리프를 입력하세요 - 제작 목표, 타깃, 핵심 메시지, 레퍼런스 등",
  },
  "brief.attachHint": { en: "IMG · PDF DROP", ko: "이미지 · PDF 드롭" },
  "brief.briefImages": { en: "BRIEF_IMAGES", ko: "브리프 이미지" },
  "brief.drop": { en: "+DROP", ko: "+드롭" },
  "brief.pdfExtractFailed": { en: "PDF_EXTRACT_FAILED - SCAN IMG NOT SUPPORTED", ko: "PDF 추출 실패 - 스캔 이미지는 지원하지 않습니다" },
  "brief.refDropVideo": { en: "DRAG OR CLICK · IMG/VIDEO · MAX 8", ko: "드래그 또는 클릭 · 이미지/영상 · 최대 8개" },
  "brief.refDropImageOnly": { en: "DRAG OR CLICK · IMG ONLY · MAX 8", ko: "드래그 또는 클릭 · 이미지만 · 최대 8개" },
  "brief.referenceNote": { en: "Reference Note", ko: "레퍼런스 노트" },
  "brief.referenceNoteAdd": { en: "Add reference note", ko: "레퍼런스 노트 추가" },
  "brief.referenceNoteEdit": { en: "Edit reference note", ko: "레퍼런스 노트 수정" },
  "brief.referenceTimeRange": { en: "Time range", ko: "관심 구간" },
  "brief.referenceFocusPoints": { en: "Points to focus on", ko: "중점적으로 볼 포인트" },
  "brief.referenceNotePlaceholder": {
    en: "- How the weapon enters via the scan line\n- Timing of the UI overlay",
    ko: "- 스캔 라인을 통해 무기가 등장하는 방식\n- UI 오버레이가 나타나는 타이밍",
  },
  "brief.referenceRangeError": {
    en: "Invalid format - frame sampling will stay on the full clip (expected e.g. 00:12~00:15). Click Save again to keep text only.",
    ko: "형식이 올바르지 않습니다. 프레임 샘플링은 전체 클립 기준으로 유지됩니다. (예: 00:12~00:15) 텍스트만 저장하려면 저장을 한 번 더 누르세요.",
  },
  "brief.clear": { en: "Clear", ko: "지우기" },
  "brief.youtubePlaceholder": { en: "Paste YouTube URL & press Enter", ko: "YouTube URL을 붙여넣고 Enter" },
  "brief.add": { en: "ADD", ko: "추가" },
  "brief.imageOnlyMode": { en: "IMG-ONLY MODE · CHANGE MODEL FOR LINK / VIDEO", ko: "이미지 전용 모드 · 링크/영상은 모델 변경 필요" },
  "brief.imageOnlyModeTitle": {
    en: "Switch to GPT-5.x in the header to enable links & video uploads",
    ko: "링크와 영상 업로드를 사용하려면 상단에서 GPT-5.x로 변경하세요",
  },
  "brief.ignored": { en: "IGNORED", ko: "제외됨" },
  "brief.addMoreReferences": { en: "Add more references", ko: "레퍼런스 추가" },
  "brief.ignoredByModel": {
    en: "{count} ITEM(S) IGNORED - UNSUPPORTED BY CURRENT MODEL",
    ko: "현재 모델에서 지원하지 않아 {count}개 항목이 제외됨",
  },
  "brief.nextStepTitle": { en: "Choose next step", ko: "다음 단계 선택" },
  "brief.nextStepDesc": {
    en: "Registering assets (characters, items, backgrounds) first helps the agent build more detailed shots.",
    ko: "먼저 에셋(캐릭터, 아이템, 배경)을 등록하면 Agent가 더 구체적인 컷을 구성할 수 있습니다.",
  },
  "brief.nextStepAssetsTitle": { en: "Set Up Assets First", ko: "에셋 먼저 설정" },
  "brief.nextStepAssetsDesc": {
    en: "Register characters, items, backgrounds then go to Ideation",
    ko: "캐릭터, 아이템, 배경을 등록한 뒤 Ideation으로 이동",
  },
  "brief.nextStepIdeationTitle": { en: "Go to Ideation Directly", ko: "바로 Ideation으로 이동" },
  "brief.nextStepIdeationDesc": {
    en: "Start building the story without assets",
    ko: "에셋 없이 바로 스토리 구성을 시작",
  },
  "brief.ideaPlaceholder": { en: "Shots, moods, and references - feel free to share.", ko: "컷, 무드, 레퍼런스 아이디어를 자유롭게 입력하세요." },

  "agent.sceneComposition": { en: "Shot Composition", ko: "컷 구성" },
  "agent.moodIdeation": { en: "Mood Ideation", ko: "무드 레퍼런스" },
  "agent.split": { en: "Split", ko: "분할" },
  "agent.splitOn": { en: "Split On", ko: "분할 보기" },
  "agent.noScenesYet": { en: "No shots yet", ko: "아직 컷이 없습니다" },
  "agent.noScenesDesc": {
    en: "Chat with Agent to start building storyboard shots. If you already sent a version to Conti, use Load Version to bring it back. Shot sketches live per-shot inside the Conti tab now.",
    ko: "Agent와 대화해 스토리보드 컷 구성을 시작하세요. 이미 Conti로 보낸 버전이 있다면 버전 불러오기로 다시 가져올 수 있습니다. 컷별 스케치는 Conti 탭에서 관리됩니다.",
  },
  "agent.welcomeNoBrief": {
    en: "Hi, I'm Agent.\nNo brief analysis found - you can describe your project directly.\nWhat kind of video are you planning?",
    ko: "안녕하세요, Agent입니다.\n아직 브리프 분석이 없어요. 프로젝트 내용을 바로 설명해주셔도 됩니다.\n어떤 영상을 기획하고 있나요?",
  },
  "agent.totalSeconds": { en: "Total {seconds}s", ko: "총 {seconds}s" },
  "agent.draftScenes": { en: "{count} DRAFT SHOTS", ko: "DRAFT 컷 {count}개" },
  "agent.clickToEdit": { en: "Click to edit", ko: "클릭해서 수정" },
  "agent.rightPanel": { en: "Right panel", ko: "오른쪽 패널" },
  "agent.singleViewTitle": { en: "Switch to single view", ko: "단일 보기로 전환" },
  "agent.splitViewTitle": { en: "Show Shot + Mood side by side", ko: "컷과 무드를 나란히 보기" },
  "agent.chatPlaceholder": { en: "Type a message... (@tag characters)", ko: "메시지를 입력하세요... (@로 에셋 태그)" },
  "agent.attachImages": { en: "Attach images (max 4)", ko: "이미지 첨부 (최대 4장)" },
  "agent.collapseChat": { en: "Collapse chat", ko: "채팅 접기" },
  "agent.expandChat": { en: "Expand chat", ko: "채팅 펼치기" },
  "agent.craftingScenario": { en: "Agent is crafting your scenario...", ko: "Agent가 시나리오를 구성 중입니다..." },
  "agent.imageColumnCollapsed": { en: "Image column is auto-collapsed because the panel is too narrow", ko: "패널이 좁아 이미지 열이 자동으로 접혔습니다" },
  "agent.hideImages": { en: "Hide images", ko: "이미지 숨기기" },
  "agent.showImages": { en: "Show images", ko: "이미지 보기" },
  "agent.confirmedScenes": { en: "Confirmed shots", ko: "확정된 컷" },
  "agent.finalCommitHint": { en: "Final commit happens when you turn the draft into shot cards.", ko: "draft를 컷 카드로 만들 때 최종 반영됩니다." },
  "agent.sceneDescriptionPlaceholder": { en: "Shot description... (@tag to reference assets)", ko: "컷 설명... (@로 에셋 참조)" },
  "agent.sceneDescriptionEmpty": { en: "Shot description... (@ to tag assets)", ko: "컷 설명... (@로 에셋 태그)" },
  "agent.locationPlaceholder": { en: "Enter location (@background tag)", ko: "장소 입력 (@배경 태그)" },
  "agent.enterLocation": { en: "+ Enter location", ko: "+ 장소 입력" },
  "agent.camera": { en: "Camera", ko: "카메라" },
  "agent.mood": { en: "Mood", ko: "무드" },
  "agent.location": { en: "Location", ko: "장소" },
  "agent.duration": { en: "Duration", ko: "길이" },
  "agent.enterField": { en: "+ Enter {label}", ko: "+ {label} 입력" },

  "mood.contextAllScenes": { en: "All shots ({count})", ko: "전체 컷 ({count})" },
  "mood.contextBriefBased": { en: "Brief-based", ko: "Brief 기반" },
  "mood.generatedToast": { en: "{count} mood images generated", ko: "무드 이미지 {count}개 생성됨" },
  "mood.generatedPartialToast": { en: "{done} of {total} mood images generated", ko: "무드 이미지 {total}개 중 {done}개 생성됨" },
  "mood.generatedPartialDesc": {
    en: "Some images could not be generated. Try Prompt only mode, or simplify the shot text/reference images.",
    ko: "일부 이미지는 생성되지 않았습니다. 프롬프트만 모드로 바꾸거나 컷 문구/참조 이미지를 단순화해보세요.",
  },
  "mood.generationFailed": { en: "Mood generation failed", ko: "무드 이미지 생성 실패" },
  "mood.safetyRejectedTitle": { en: "Blocked by safety filter", ko: "안전 필터로 생성이 차단됨" },
  "mood.safetyRejectedDesc": {
    en: "The prompt or reference image was rejected by the image model safety system. Try Prompt only mode, or revise the shot text/reference images.",
    ko: "프롬프트 또는 참조 이미지가 이미지 모델의 안전 필터에 의해 거절되었습니다. 프롬프트만 모드로 바꾸거나 컷 문구/참조 이미지를 수정해보세요.",
  },
  "mood.allGenerationFailedDesc": {
    en: "No images were generated. Try again with a shorter prompt, fewer references, or Prompt only mode.",
    ko: "생성된 이미지가 없습니다. 더 짧은 프롬프트, 더 적은 참조 이미지, 또는 프롬프트만 모드로 다시 시도해보세요.",
  },
  "mood.attachedToast": { en: "Image attached to Shot #{scene}", ko: "이미지를 컷 #{scene}에 연결했습니다" },
  "mood.detachedToast": { en: "Detached from Shot #{scene}", ko: "컷 #{scene}에서 연결 해제했습니다" },
  "mood.registerAssetsFirst": { en: "Register assets first", ko: "먼저 에셋을 등록하세요" },
  "mood.assetsWithImagesRequired": { en: "Assets with images are required", ko: "이미지가 있는 에셋이 필요합니다" },
  "mood.default": { en: "DEFAULT", ko: "기본" },
  "mood.gpt15WithRefs": { en: "GPT Image 1.5 · Image refs", ko: "GPT Image 1.5 · 이미지 참조" },
  "mood.gpt15TextOnly": { en: "GPT Image 1.5 · Prompt only", ko: "GPT Image 1.5 · 프롬프트만" },
  "mood.gpt15WithRefsDesc": { en: "Default · Reads asset images", ko: "기본 · 에셋 이미지를 읽음" },
  "mood.gpt15TextOnlyDesc": { en: "Fastest · Uses prompt only", ko: "가장 빠름 · 프롬프트만 사용" },
  "mood.disabledModelDesc": { en: "Disabled for Mood Reference", ko: "무드 레퍼런스에서는 비활성화됨" },
  "mood.disabledModelTitle": { en: "Model disabled", ko: "비활성화된 모델" },
  "mood.registerAssetImagesFirst": { en: "Register asset images first", ko: "먼저 에셋 이미지를 등록하세요" },
  "mood.allScenes": { en: "All shots", ko: "전체 컷" },
  "mood.briefBased": { en: "Brief-based", ko: "Brief 기반" },
  "mood.saved": { en: "Saved", ko: "저장됨" },
  "mood.savedCount": { en: "Saved {count}", ko: "저장됨 {count}" },
  "mood.noSavedImages": { en: "No saved images", ko: "저장된 이미지가 없습니다" },
  "mood.noMoodImages": { en: "No mood images yet", ko: "아직 무드 이미지가 없습니다" },
  "mood.saveImagesHint": { en: "Save images with the heart button", ko: "하트 버튼으로 이미지를 저장하세요" },
  "mood.generateHint": { en: "Select a shot above and generate mood images", ko: "위에서 컷을 선택하고 무드 이미지를 생성하세요" },
  "mood.attachToScene": { en: "Attach to shot", ko: "컷에 연결" },
  "mood.detachScene": { en: "Detach #{scene}", ko: "#{scene} 연결 해제" },
  "mood.linked": { en: "linked", ko: "연결됨" },
  "mood.selected": { en: "{count} selected", ko: "{count}개 선택됨" },
  "mood.deselect": { en: "Deselect", ko: "선택 해제" },
  "mood.linkedToScene": { en: "Linked to #{scene}", ko: "#{scene}에 연결됨" },
  "mood.sendToChat": { en: "Send to chat", ko: "채팅으로 보내기" },
  "mood.deleteImage": { en: "Delete image", ko: "이미지 삭제" },
  "mood.deleteImagesTitle": { en: "Delete images?", ko: "이미지를 삭제할까요?" },
  "mood.deleteImagesDesc": {
    en: "{count} of the selected images are linked to shots ({scenes}).\n\nDeleting them will also remove the images from those shots. Continue?",
    ko: "선택한 이미지 중 {count}개가 컷에 연결되어 있습니다 ({scenes}).\n\n삭제하면 해당 컷에서도 이미지가 제거됩니다. 계속할까요?",
  },
  "mood.delete": { en: "Delete", ko: "삭제" },
  "mood.deleteAll": { en: "Delete All", ko: "전체 삭제" },
  "mood.generate": { en: "Generate", ko: "생성" },
  "mood.generateInProgressTitle": { en: "{count} batch in progress - click to start another", ko: "{count}개 배치 생성 중 - 클릭하면 추가 생성" },

  "conti.newVersion": { en: "New Version", ko: "새 버전" },
  "conti.versionName": { en: "Version name", ko: "버전 이름" },
  "conti.startMethod": { en: "Start method", ko: "시작 방식" },
  "conti.copyCurrentScenes": { en: "Copy current shots", ko: "현재 컷 복사" },
  "conti.copyCurrentScenesDesc": { en: "Duplicate shot structure, regenerate conti", ko: "컷 구조를 복사하고 콘티는 다시 생성" },
  "conti.startFresh": { en: "Start fresh", ko: "새로 시작" },
  "conti.startFreshDesc": { en: "Develop a new scenario from Ideation tab", ko: "Ideation 탭에서 새 시나리오 구성" },
  "conti.creating": { en: "Creating...", ko: "생성 중..." },
  "conti.createVersion": { en: "Create Version", ko: "버전 생성" },
  "conti.createdToast": { en: "\"{name}\" created", ko: "\"{name}\" 생성됨" },
  "conti.creationFailed": { en: "Creation failed", ko: "생성 실패" },
  "conti.generateAll": { en: "Generate All", ko: "전체 생성" },
  "conti.highlight": { en: "Highlight", ko: "Highlight" },
  "conti.markHighlight": { en: "Mark as Highlight", ko: "Highlight로 표시" },
  "conti.unmarkHighlight": { en: "Unmark Highlight", ko: "Highlight 해제" },
  "conti.highlightHint": {
    en: "Key visual candidate. Generation gives this shot extra composition attention.",
    ko: "키비주얼 후보입니다. 생성 시 이 컷의 구도와 시선을 조금 더 신경 씁니다."
  },
  "conti.modelNanoDesc": { en: "Consistency + composition (default)", ko: "일관성 + 구도 유지 (기본)" },
  "conti.modelGptDesc": { en: "General purpose", ko: "범용 이미지 생성" },
  "conti.transfer": { en: "Transfer", ko: "스타일 적용" },
  "conti.styleTransfer": { en: "Style Transfer", ko: "스타일 적용" },
  "conti.styleTransferHelp": {
    en: "Composition and layout are preserved. Only the visual style changes.",
    ko: "구도와 레이아웃은 유지하고 시각 스타일만 변경합니다."
  },
  "conti.selectedStyle": { en: "Selected style", ko: "선택한 스타일" },
  "conti.transferSelectedOrAll": {
    en: "Transfer style to {selected} selected or all {total} shots.",
    ko: "선택한 {selected}개 또는 전체 {total}개 컷에 스타일을 적용합니다."
  },
  "conti.transferAllScenes": {
    en: "Transfer style to all {total} shots with conti images.",
    ko: "콘티 이미지가 있는 전체 {total}개 컷에 스타일을 적용합니다."
  },
  "conti.transferAll": { en: "Transfer All ({count})", ko: "전체 적용 ({count})" },
  "conti.selectedCount": { en: "Selected ({count})", ko: "선택 항목 ({count})" },
  "conti.selected": { en: "{count} Selected", ko: "{count}개 선택됨" },
  "conti.clearSelection": { en: "Clear selection", ko: "선택 해제" },
  "conti.info": { en: "Info", ko: "정보" },
  "conti.export": { en: "Export", ko: "내보내기" },
  "conti.new": { en: "New", ko: "새로 만들기" },
  "conti.versionShort": { en: "ver.{num}", ko: "버전 {num}" },
  "conti.sceneCountShort": { en: "Shots {count}", ko: "컷 {count}" },
  "conti.imageCountShort": { en: "Img {done}/{total}", ko: "이미지 {done}/{total}" },
  "conti.noDescriptionShort": { en: "{count} no desc", ko: "설명 없음 {count}" },
  "conti.generateProgressShort": { en: "GEN {done}/{total}", ko: "생성 {done}/{total}" },
  "conti.styleProgressShort": { en: "STY {done}/{total}", ko: "스타일 {done}/{total}" },
  "conti.noDescriptionGenerateAll": {
    en: "No description - excluded from Generate All",
    ko: "설명 없음 - 전체 생성에서 제외됩니다",
  },
  "conti.emptyHint": { en: "Create a shot or start a new version", ko: "컷을 만들거나 새 버전을 시작하세요" },
  "conti.addScene": { en: "Add Shot", ko: "컷 추가" },
  "conti.addTransition": { en: "Add Transition", ko: "전환 추가" },
  "conti.transitionNeedsImages": { en: "Both shots need images", ko: "양쪽 컷에 이미지가 필요합니다" },
  "conti.insertTransitionTitle": { en: "Insert transition between shots", ko: "컷 사이에 전환 삽입" },
  "conti.noScenesToSave": { en: "No shots to save", ko: "저장할 컷이 없습니다" },
  "conti.styleSelect": { en: "Style Select", ko: "스타일 선택" },
  "conti.none": { en: "None", ko: "없음" },
  "conti.defaultPhotorealistic": { en: "Default photorealistic", ko: "기본 실사 스타일" },
  "conti.upload": { en: "Upload", ko: "업로드" },
  "conti.uploading": { en: "Uploading...", ko: "업로드 중..." },
  "conti.dropImage": { en: "Drop image", ko: "이미지 드롭" },
  "conti.releaseToUpload": { en: "Release to upload", ko: "놓으면 업로드됩니다" },
  "conti.dragDropClick": { en: "Drag & drop or click", ko: "드래그 앤 드롭 또는 클릭" },
  "conti.onlyImageFiles": { en: "Only image files can be uploaded.", ko: "이미지 파일만 업로드할 수 있습니다." },
  "conti.apply": { en: "Apply", ko: "적용" },
  "conti.renameVersion": { en: "Rename Version", ko: "버전 이름 변경" },
  "conti.renamed": { en: "Renamed.", ko: "이름이 변경되었습니다." },
  "conti.deleteVersion": { en: "Delete Version", ko: "버전 삭제" },
  "conti.deleteVersionDesc": { en: "Are you sure you want to delete \"{name}\"? This action cannot be undone.", ko: "\"{name}\" 버전을 삭제할까요? 이 작업은 되돌릴 수 없습니다." },
  "conti.deleteCustomStyle": { en: "Delete custom style?", ko: "커스텀 스타일을 삭제할까요?" },
  "conti.deleteCustomStyleDesc": {
    en: "\"{name}\" will be permanently removed. Projects using this style will fall back to the default.",
    ko: "\"{name}\" 스타일이 영구적으로 삭제됩니다. 이 스타일을 사용하던 프로젝트는 기본 스타일로 돌아갑니다.",
  },
  "conti.deleteFailed": { en: "Delete failed", ko: "삭제 실패" },
  "conti.uploadFailed": { en: "Upload failed", ko: "업로드 실패" },
  "conti.styleRemoved": { en: "Style removed.", ko: "스타일이 제거되었습니다." },
  "conti.styleChangeFailed": { en: "Style change failed", ko: "스타일 변경 실패" },
  "conti.styleUploaded": { en: "\"{name}\" style uploaded.", ko: "\"{name}\" 스타일이 업로드되었습니다." },
  "conti.styleApplied": { en: "\"{name}\" style applied.", ko: "\"{name}\" 스타일이 적용되었습니다." },
  "conti.styleTransferComplete": { en: "Style transfer complete!", ko: "스타일 적용 완료!" },
  "conti.styleTransferFailed": { en: "Style transfer failed", ko: "스타일 적용 실패" },
  "conti.styleTransferPartialFailed": {
    en: "Style transfer: {failed} of {total} shots failed",
    ko: "스타일 적용: {total}개 중 {failed}개 컷 실패"
  },
  "conti.sceneFailureReason": { en: "Shot #{scene}: {reason}", ko: "컷 #{scene}: {reason}" },
  "conti.queued": { en: "Queued", ko: "대기 중" },
  "conti.translating": { en: "Translating...", ko: "해석 중..." },
  "conti.building": { en: "Building...", ko: "구성 중..." },
  "conti.generating": { en: "Generating...", ko: "생성 중..." },
  "conti.styleTransferring": { en: "Style transfer...", ko: "스타일 적용 중..." },
  "conti.clearStyle": { en: "Clear style", ko: "스타일 지우기" },
  "conti.duplicateScene": { en: "Duplicate shot", ko: "컷 복제" },
  "conti.compareVersions": { en: "Compare versions", ko: "버전 비교" },
  "conti.inpaint": { en: "Inpaint", ko: "인페인트" },
  "conti.setAsThumbnail": { en: "Set as Thumbnail", ko: "썸네일로 설정" },
  "conti.adjustImage": { en: "Adjust Image", ko: "이미지 조정" },
  "conti.outputFrame": { en: "{format} output frame", ko: "{format} 출력 프레임" },
  "conti.reset": { en: "Reset", ko: "초기화" },
  "conti.capturing": { en: "Capturing...", ko: "캡처 중..." },
  "conti.setAsImage": { en: "Set as Image", ko: "이미지로 설정" },
  "conti.variants": { en: "Variants", ko: "변형" },
  "conti.relight": { en: "Relight", ko: "조명 변경" },
  "conti.changeAngle": { en: "Change Angle", ko: "앵글 변경" },
  "variant.noSourceImage": { en: "No source image for this shot.", ko: "이 컷에 원본 이미지가 없습니다." },
  "variant.closeEsc": { en: "Close (Esc)", ko: "닫기 (Esc)" },
  "variant.direction": { en: "Direction", ko: "방향" },
  "variant.azimuth": { en: "Az", ko: "방위" },
  "variant.elevation": { en: "Elev", ko: "고도" },
  "variant.back": { en: "Back", ko: "뒤" },
  "variant.front": { en: "Front", ko: "앞" },
  "variant.top": { en: "Top", ko: "위" },
  "variant.bottom": { en: "Bottom", ko: "아래" },
  "variant.intensity": { en: "Intensity", ko: "광량" },
  "variant.softness": { en: "Softness", ko: "부드러움" },
  "variant.ambientFill": { en: "Ambient fill", ko: "환경광 보정" },
  "variant.hard": { en: "hard", ko: "강함" },
  "variant.medium": { en: "medium", ko: "중간" },
  "variant.soft": { en: "soft", ko: "부드러움" },
  "variant.deepShadows": { en: "deep shadows", ko: "짙은 그림자" },
  "variant.balanced": { en: "balanced", ko: "균형" },
  "variant.flat": { en: "flat", ko: "평탄함" },
  "variant.lightColor": { en: "Light color", ko: "조명 색상" },
  "variant.customColor": { en: "Custom color", ko: "사용자 색상" },
  "variant.customHex": { en: "Custom {hex}", ko: "사용자 색상 {hex}" },
  "variant.quickPreset": { en: "Quick preset", ko: "빠른 프리셋" },
  "variant.overwritesControls": { en: "Overwrites controls", ko: "현재 설정을 덮어씀" },
  "variant.additionalNotes": { en: "Additional notes", ko: "추가 메모" },
  "variant.notes": { en: "Notes", ko: "메모" },
  "variant.optional": { en: "Optional", ko: "선택 사항" },
  "variant.relightNotesPlaceholder": {
    en: "e.g. practical lamps visible in background, subtle haze, film grain...",
    ko: "예: 배경에 보이는 실내등, 은은한 안개, 필름 그레인..."
  },
  "variant.changeAngleNotesPlaceholder": { en: "anything else worth telling the model", ko: "모델에 추가로 전달할 내용" },
  "variant.showGeneratedPrompt": { en: "Show generated prompt", ko: "생성 프롬프트 보기" },
  "variant.hideGeneratedPrompt": { en: "Hide generated prompt", ko: "생성 프롬프트 숨기기" },
  "variant.orbitCamera": { en: "Orbit camera", ko: "카메라 궤도" },
  "variant.resetAllTitle": { en: "Reset all controls to 0", ko: "모든 값을 0으로 초기화" },
  "variant.reset": { en: "Reset", ko: "초기화" },
  "variant.yaw": { en: "Yaw", ko: "좌우 회전" },
  "variant.pitch": { en: "Pitch", ko: "상하 각도" },
  "variant.zoom": { en: "Zoom", ko: "줌" },
  "variant.dolly": { en: "Dolly", ko: "돌리" },
  "variant.down": { en: "Down", ko: "아래" },
  "variant.up": { en: "Up", ko: "위" },
  "variant.pullBack": { en: "Pull back", ko: "뒤로" },
  "variant.pushIn": { en: "Push in", ko: "앞으로" },
  "variant.same": { en: "same", ko: "동일" },
  "variant.submitAndCloseTitle": {
    en: "Submit and close - generation continues on the shot card.",
    ko: "적용 후 닫습니다. 생성은 컷 카드에서 계속 진행됩니다."
  },
  "variant.doubleClickResetTitle": { en: "Double-click to reset to 0", ko: "더블클릭하면 0으로 초기화" },
  "conti.cameraVariations": { en: "Camera Variations", ko: "카메라 변형" },
  "conti.unavailable": { en: "Unavailable", ko: "사용 불가" },
  "conti.uploadImage": { en: "Upload Image", ko: "이미지 업로드" },
  "conti.deleteImage": { en: "Delete image", ko: "이미지 삭제" },
  "conti.deleteScene": { en: "Delete shot", ko: "컷 삭제" },
  "conti.transitionTechnique": { en: "Transition Technique", ko: "전환 기법" },
  "conti.selectTechnique": { en: "Select a technique", ko: "기법 선택" },
  "conti.transitionGuide": { en: "Direction guide", ko: "연출 가이드" },
  "conti.sceneDescriptionPlaceholder": { en: "Enter shot description... (@tag for assets)", ko: "컷 설명 입력... (@로 에셋 태그)" },
  "conti.sceneDescriptionEmpty": { en: "Enter shot description...", ko: "컷 설명을 입력하세요..." },
  "conti.camera": { en: "Camera", ko: "카메라" },
  "conti.mood": { en: "Mood", ko: "무드" },
  "conti.location": { en: "Location", ko: "장소" },
  "conti.duration": { en: "Duration", ko: "길이" },
  "conti.enterCamera": { en: "+ Enter camera", ko: "+ 카메라 입력" },
  "conti.enterMood": { en: "+ Enter mood", ko: "+ 무드 입력" },
  "conti.enterLocation": { en: "+ Enter location", ko: "+ 장소 입력" },
  "conti.enterTime": { en: "+ Enter time", ko: "+ 시간 입력" },

  "studio.transition": { en: "Transition", ko: "전환" },
  "studio.camera": { en: "Camera", ko: "카메라" },
  "studio.mood": { en: "Mood", ko: "무드" },
  "studio.location": { en: "Location", ko: "장소" },
  "studio.duration": { en: "Duration", ko: "길이" },
  "studio.description": { en: "Description", ko: "설명" },
  "studio.editorHelp": { en: "Draw annotations on the conti image. Use the toolbar at the bottom of the canvas.", ko: "콘티 이미지 위에 주석을 그릴 수 있습니다. 캔버스 하단 툴바를 사용하세요." },
  "studio.editorHelp2": { en: "Annotations are local-only and do not modify the original image. Use Save to download a merged PNG.", ko: "주석은 로컬에서만 표시되며 원본 이미지를 변경하지 않습니다. 저장하면 병합된 PNG를 다운로드합니다." },
  "studio.references": { en: "References", ko: "레퍼런스" },
  "studio.noHistory": { en: "No history yet", ko: "아직 히스토리가 없습니다" },
  "studio.previous": { en: "Previous", ko: "이전 버전" },
  "studio.ago": { en: "{count} ago", ko: "{count}번째 이전" },
  "studio.current": { en: "Current", ko: "현재" },
  "studio.preview": { en: "Preview", ko: "미리보기" },
  "studio.restore": { en: "Restore", ko: "복원" },
  "studio.deleteFromHistory": { en: "Delete from history", ko: "히스토리에서 삭제" },
  "studio.historyDeleted": { en: "Shot #{scene} history deleted", ko: "컷 #{scene} 히스토리가 삭제되었습니다" },
  "studio.sceneRestored": { en: "Shot #{scene} restored", ko: "컷 #{scene}이 복원되었습니다" },
  "studio.imageReplaced": { en: "Image replaced", ko: "이미지가 교체되었습니다" },
  "studio.setAsConti": { en: "Set as conti image", ko: "콘티 이미지로 설정되었습니다" },
  "studio.addedToEditRefs": { en: "Added to Edit references", ko: "Edit 레퍼런스에 추가되었습니다" },
  "studio.useAsConti": { en: "Use as Conti", ko: "Conti로 사용" },
  "studio.replace": { en: "Replace", ko: "교체" },
  "studio.addToEdit": { en: "Add to Edit", ko: "Edit에 추가" },
  "studio.clickPreview": { en: "Click an image to preview", ko: "이미지를 클릭해 미리보기" },
  "studio.noReferenceImages": { en: "No reference images available", ko: "사용 가능한 레퍼런스 이미지가 없습니다" },
  "studio.sceneReference": { en: "Shot Reference", ko: "컷 레퍼런스" },
};

export const getUiCopy = (key: string, lang: UiLanguage) => UI_COPY[key]?.[lang] ?? UI_COPY[key]?.en ?? key;
